version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: server
    expose: 
      - '8080'
    ports: 
      - '8080:8080'
    command: node build/index.js
    restart: unless-stopped
    env_file: .env